navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0

    broadcast_cartesian_transform: false
    broadcast_cartesian_transform_as_parent_frame: false
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false
    
    magnetic_declination_radians: 0.2237512101057
    yaw_offset: 0
    zero_altitude: true

