navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: false
    broadcast_utm_transform_as_parent_frame: false
    publish_filtered_gps: true
    filtered_gps_topic: /gps/filtered
    use_odometry_yaw: false
    wait_for_datum: false
    base_link_frame: base_link      # Twój główny frame łodzi
    gps_frame: gps_link             # fizyczny frame GPS na łodzi
    datum: [-33.72275180, 150.67395124, 0.0]
